### ISSUE TITLE
这是一个路径的错误

### ISSUE THREAD

**Issue by NewCicada** [pengyw97/vue-mimall#1]
这是一个错误的路径
您的router路由文件夹下的导入使用了大写的文件名
而pages下的是小写
![路径错误](https://user-images.githubusercontent.com/51705726/182885133-dd8bb8bb-6035-4bbd-bc79-60997ddd86fc.png)

**Comment by dark9wesley** [comment]
非常感谢！

**Comment by dark9wesley** [comment]
已修复，感谢指正
